on:
  issues:
    types: [opened]

jobs:
  add-name:
    name: Add Name
    runs-on: ubuntu-latest

    if: github.event.issue.title == '_add_my_name_'

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set env vars
        run: echo "USER_NAME=${{ github.event.issue.user.login }}" >> $GITHUB_ENV

      - name: Rendering
        run: bash .husky/add-name.sh $USER_NAME

      - name: Updating Repo
        run: bash .husky/update-repo.sh

      - name: Issue Resolved
        if: ${{ always() }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          state: 'closed'