on:
  push:
    branches:
      - 'main'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Render with latest visitors.json data
        run: deno run --allow-write --allow-read src/index.ts --render

      - name: Updating Repo
        run: bash .husky/update-repo.sh